<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
		<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
		<WasmBuildNative>true</WasmBuildNative>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release' AND '$(Publish)' == 'true'">
		<RunAOTCompilation>true</RunAOTCompilation> 
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Features\Bible\ActionComponents\Find\**" />
		<Compile Remove="Features\ScrollSpy\**" />
		<Content Remove="Features\Bible\ActionComponents\Find\**" />
		<Content Remove="Features\ScrollSpy\**" />
		<EmbeddedResource Remove="Features\Bible\ActionComponents\Find\**" />
		<EmbeddedResource Remove="Features\ScrollSpy\**" />
		<None Remove="Features\Bible\ActionComponents\Find\**" />
		<None Remove="Features\ScrollSpy\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Ardalis.SmartEnum" />
		<PackageReference Include="Blazored.LocalStorage" />
		<PackageReference Include="Blazored.Toast" />
		<PackageReference Include="Blazored.Typeahead" />
		<PackageReference Include="Dapper" />
		<PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="Sentry.AspNetCore.Blazor.WebAssembly" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Serilog.Sinks.BrowserConsole" />
		<PackageReference Include="SqliteWasmBlazor" />
		<PackageReference Include="Toolbelt.Blazor.PWA.Updater" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RCL\RCL.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Features\Lists\MitzvahPage\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Features\Bible\ActionComponents\VerseAndID.cs" />
	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<!-- Optional but often helps with trimming issues -->
		<PublishTrimmed>false</PublishTrimmed>
	</PropertyGroup>

</Project>
